project/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :album_informations # ,only: %i[index show]
  resources :songs
  resources :albums

  get 'search_results', to: 'search#results', as: 'search_results'
  get '/pages/:page' => 'pages#show'
  root to: 'albums#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

project/app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  has_many :songs
  has_one :album_information
  validates :artist, :album_title, presence: true
end

project/app/models/album_information.rb
# frozen_string_literal: true

class AlbumInformation < ApplicationRecord
  belongs_to :album
  validates :date, :play_count, presence: true
  validates :play_count, numericality: { only_integer: true }
end

project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project/app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true
  belongs_to :album
end

project/app/controllers/album_informations_controller.rb
# frozen_string_literal: true

class AlbumInformationsController < ApplicationController
  before_action :set_album_information, only: %i[show edit update destroy]

  # GET /album_informations
  # GET /album_informations.json
  def index
    @album_informations = AlbumInformation.all
  end

  # GET /album_informations/1
  # GET /album_informations/1.json
  def show
    @album_information = AlbumInformation.find(params[:id])
  end

  # GET /album_informations/new
  def new
    @album_information = AlbumInformation.new
  end

  # GET /album_informations/1/edit
  def edit; end

  # POST /album_informations
  # POST /album_informations.json
  def create
    @album_information = AlbumInformation.new(album_information_params)

    respond_to do |format|
      if @album_information.save
        format.html { redirect_to @album_information, notice: 'Album information was successfully created.' }
        format.json { render :show, status: :created, location: @album_information }
      else
        format.html { render :new }
        format.json { render json: @album_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /album_informations/1
  # PATCH/PUT /album_informations/1.json
  def update
    respond_to do |format|
      if @album_information.update(album_information_params)
        format.html { redirect_to @album_information, notice: 'Album information was successfully updated.' }
        format.json { render :show, status: :ok, location: @album_information }
      else
        format.html { render :edit }
        format.json { render json: @album_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /album_informations/1
  # DELETE /album_informations/1.json
  def destroy
    @album_information.destroy
    respond_to do |format|
      format.html { redirect_to album_informations_url, notice: 'Album information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_album_information
    @album_information = AlbumInformation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def album_information_params
    params.require(:album_information).permit(:play_count, :date)
  end
end

project/app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  before_action :set_album, only: %i[show edit update destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit; end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @album = Album.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def album_params
    params.require(:album).permit(:artist, :album_title)
  end
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

project/app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
   end
end

project/app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def results
    @query = params[:q]
    @album_found = Album.where('album_title LIKE ?', "%#{@query}%")
  end
end

project/app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  before_action :set_song, only: %i[show edit update destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all.page(params[:page])
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit; end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_song
    @song = Song.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def song_params
    params.require(:song).permit(:name, :album_id)
  end
end

project/app/helpers/album_informations_helper.rb
module AlbumInformationsHelper
end

project/app/helpers/albums_helper.rb
module AlbumsHelper
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/pages_helper.rb
module PagesHelper
end

project/app/helpers/search_helper.rb
module SearchHelper
end

project/app/helpers/songs_helper.rb
module SongsHelper
end

project/app/views/album_informations/_form.html.erb
<%= form_with(model: album_information, local: true) do |form| %>
  <% if album_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album_information.errors.count, "error") %> prohibited this album_information from being saved:</h2>

      <ul>
      <% album_information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :play_count %>
    <%= form.number_field :play_count %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/album_informations/edit.html.erb
<h1>Editing Album Information</h1>

<%= render 'form', album_information: @album_information %>

<%= link_to 'Show', @album_information %> |
<%= link_to 'Back', album_informations_path %>

project/app/views/album_informations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Album Informations</h1>

<table>
  <thead>
    <tr>
      <th>Play count</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @album_informations.each do |album_information| %>
      <tr>
        <td><%= album_information.play_count %></td>
        <td><%= album_information.date %></td>
        <td><%= link_to 'Show', album_information %></td>
        <td><%= link_to 'Edit', edit_album_information_path(album_information) %></td>
        <td><%= link_to 'Destroy', album_information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album Information', new_album_information_path %>

project/app/views/album_informations/new.html.erb
<h1>New Album Information</h1>

<%= render 'form', album_information: @album_information %>

<%= link_to 'Back', album_informations_path %>

project/app/views/album_informations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Play count:</strong>
  <%= @album_information.play_count %>
</p>

<p>
  <strong>Date:</strong>
  <%= @album_information.date %>
</p>

<%= link_to 'Edit', edit_album_information_path(@album_information) %> |
<%= link_to 'Back', album_informations_path %>

project/app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :album_title %>
    <%= form.text_field :album_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

project/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Album title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= link_to album.artist, album %></td>
        <td><%= album.album_title %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

project/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

project/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Album title:</strong>
  <%= @album.album_title %>
</p>


<p>
  <strong>Album info:</strong>
  <%= @album_information %>
</p>


<h3>Track list </h3 >
<tbody>
    <%= @album.songs.each do |song| %>

      <tr>
        <td><%= song.name  %></td><br>
       </tr>
    <% end %>

  </tbody>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <head>
    <title>Project</title>
     <nav class="navbar navbar-light bg-light">
    <%= link_to 'Back', albums_path %>
    <a class="navbar-brand" href= "/albums/" >Albums</a>
    <a class="navbar-brand" href= "/songs/">Songs</a>
    <a class="navbar-brand" href="/pages/about/">About</a>

<%= form_tag(search_results_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>
  </nav>



  </head>

  <body>

    <%= yield %>
  </body>
</html>

project/app/views/pages/about.html.erb

<html>
<body>

<h1>Describing data set</h1>
<p>The album model contains the artist and title. </p>
<p>A Album has many songs</p>
<p>One album has one album information displaying the play count</p>
<%# <%= image_tag ('ERD.PNG')%>


</body>
</html>

project/app/views/search/results.html.erb
<h1>Matching albums results</h1>



<% @album_found.each do |album| %>
<h3><%= album.album_title %></h3>
<%end%>

project/app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :album_id %>
    <%= form.text_field :album_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

project/app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>

      <tr>
        <td><%= song.name %></td>

        <td><%= link_to song.album.album_title, song.album %></td>
        </tr>
    <% end %>
  </tbody>

</table>
 <%= paginate @songs%>
<br>

<%= link_to 'New Song', new_song_path %>

project/app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

project/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>